"""empty message

Revision ID: 838e1526eca3
Revises: f964535bf7b5
Create Date: 2022-01-04 12:24:00.906988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '838e1526eca3'
down_revision = 'f964535bf7b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_N_email_news_email', table_name='N_email')
    op.create_index(op.f('ix_N_email_news_email'), 'N_email', ['news_email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_N_email_news_email'), table_name='N_email')
    op.create_index('ix_N_email_news_email', 'N_email', ['news_email'], unique=False)
    # ### end Alembic commands ###
